### ISSUE TITLE
options.shared=false should be default option

### ISSUE THREAD

**Issue by adityapatadia** [kornelski/http-cache-semantics#13]
Lot of people should use this to cache on their own servers and not mean to use this as shared cache. Probably the `shared=false` should be default for this library.

**Comment by adityapatadia** [comment]
What do you think of this @kornelski

**Comment by kornelski** [comment]
No, the choice of shared is deliberate, because it's safer — you don't risk mixing up private data.

**Comment by adityapatadia** [comment]
Ok.
