### ISSUE TITLE
Are empty header values equivalent to absent ones?

### ISSUE THREAD

**Issue by ohwillie** [kornelski/http-cache-semantics#15]
There are a lot of falsey checks in this library rather than undefined checks. [Here's one, for example.](https://github.com/kornelski/http-cache-semantics/blob/d5c28b7a20a32419c973485a81c886b8c60ee1d0/index.js#L88) I'm wondering if these should be switched to null/undefined checks (`x == null`) as it appears that empty header values are valid according to the HTTP RFC. I'm wondering this is that I'm working with an API that is behaving weirdly (returns `Pragma: no-cache` alongside `Cache-Control: `) when I send over a `Cache-Control: max-age=3600` header in the request, which is causing this library to consider the response to not be cacheable. Thx!

**Comment by kornelski** [comment]
Oh, interesting edge case. I guess "header present" does include `""` values, so a stricter change would be ok.
