### ISSUE TITLE
Revalidated policy contains new response headers even if not modified

### ISSUE THREAD

**Issue by szmarczak** [kornelski/http-cache-semantics#26]
```
ORIGINAL POLICY {
  'content-type': 'application/json',
  'last-modified': 'Wed, 27 Nov 2019 01:56:57 GMT',
  'content-encoding': 'gzip',
  age: '449457',
  date: 'Sun, 08 Dec 2019 14:21:24 GMT',
  warning: '113 - "rfc7234 5.5.4"'
}
REVALIDATED POLICY modified=false {
  age: '449457',
  date: 'Sun, 08 Dec 2019 14:21:24 GMT'
}
```

I just placed

```js
console.log('ORIGINAL POLICY', CachePolicy.fromObject(revalidate.cachePolicy).responseHeaders());
console.log('REVALIDATED POLICY', `modified=${revalidatedPolicy.modified}`,  revalidatedPolicy.policy.responseHeaders());
```

after this line:

https://github.com/lukechilds/cacheable-request/blob/147924989daf078b071be3aa4ad67cc6702512f0/src/index.js#L87

I will include some reproducible code soon.

**Comment by kornelski** [comment]
This is the correct behavior. 304 response is supposed to be able to update headers of the cached response.

**Comment by szmarczak** [comment]
Yeah, but it overrides **everything**. Note that `content-encoding` contains `gzip` in the first policy. The latter is missing it.

**Comment by szmarczak** [comment]
This causes Got to serve raw response instead of the decompressed one as `cacheable-request` uses the overridden headers.

**Comment by kornelski** [comment]
It's supposed to be keeping all old headers, and never overwrites `content-encoding`:

https://github.com/kornelski/http-cache-semantics/blob/71601466cfe1e17a5be85f0b5915704f6a494957/index.js#L629-L635

Maybe the bug is in Got?

**Comment by szmarczak** [comment]
This proves that it's a bug in `http-cache-semantics`:

https://runkit.com/szmarczak/5dee6192da9f5d001b79a221

**Comment by kornelski** [comment]
`Accept-Encoding` is a *request* header, and you're calling `responseHeaders()`.

**Comment by kornelski** [comment]
However, `content-type` is missing, and that probably needs fixing.

**Comment by szmarczak** [comment]
I meant `content-type` :P Sorry, sometimes I confuse these two.

**Comment by szmarczak** [comment]
> However, content-type is missing, and that probably needs fixing.

Probably? Definitely! :D

**Comment by szmarczak** [comment]
The thing is that 304 is disallowed:

https://github.com/kornelski/http-cache-semantics/blob/71601466cfe1e17a5be85f0b5915704f6a494957/index.js#L577-L578

https://github.com/kornelski/http-cache-semantics/blob/71601466cfe1e17a5be85f0b5915704f6a494957/index.js#L616-L625

**Comment by szmarczak** [comment]
The thing is that `if-modified-since` is not supported:

```js
            // If the new response does not include any form of validator (such as in the case where
            // a client generates an If-Modified-Since request from a source other than the Last-Modified
            // response header field), and there is only one stored response, and that stored response also
            // lacks a validator, then that stored response is selected for update.
```

**Comment by szmarczak** [comment]
Consider using a code coverage service - it will help a lot! :)

**Comment by szmarczak** [comment]
`notModifiedResponseHeaders` is not a correct function name. It checks if **the response** has been modified, not the headers.

**Comment by szmarczak** [comment]
I have done more digging. The second response doesn't include any validation header so this is correct behavior.
