### ISSUE TITLE
Update docs and feedback link for Rust version

### ISSUE THREAD

**Issue by ypoluektovich** [kornelski/http-cache-semantics#33]
1) The README at https://github.com/kornelski/rusty-http-cache-semantics is very much not up to date with the API.
2) The "homepage" link at https://crates.io/crates/http-cache-semantics points to the JS repo. At least the "repository" link is correct.
3) Please enable issues for the Rust repo.

**Comment by kornelski** [comment]
I've enabled issues in the other repo. I think the readme is up to date - please file issues with the missing bits you've found.
