### ISSUE TITLE
`policy.storable()` returns false when response status is 304

### ISSUE THREAD

**Issue by guanzo** [kornelski/http-cache-semantics#34]
I'm following your code example for revalidation https://www.npmjs.com/package/http-cache-semantics#revalidatedpolicyrevalidationrequest-revalidationresponse

My `newResponse.status` is 304, I pass the response to `oldPolicy.revalidatedPolicy()` and get a new `policy` in return. 

Now `policy.storable()` returns false and `policy.timeToLive()` returns 0, due to this condition evaluating to `false` because `this._status` is 304. https://github.com/kornelski/http-cache-semantics/blob/ed83aec75be817967cdac2663907d060fdc6adc3/index.js#L187

This makes the example code kinda funky, because you're caching the response in `letsPretendThisIsSomeCache` with a 0 ttl.

Since the resource was successfully revalidated, I expect `storable()` to return true and `timeToLive()` to return some non zero number. Is this intended?

**Comment by kornelski** [comment]
304 is not a cacheable response. It doesn't contain any data to cache. It has nothing to store.

**Comment by guanzo** [comment]
So how're we supposed to refresh the cache ttl after a 304 response, if `policy.timeToLive()` is zero? I don't understand.
In your example, you're updating the cache with a 0 ttl if the response is 304. That's not very useful.

https://github.com/kornelski/http-cache-semantics/blob/ed83aec75be817967cdac2663907d060fdc6adc3/README.md#L157-L162

**Comment by kornelski** [comment]
This method takes TTL from the 304 response and combines it with other data from the old one:

https://github.com/kornelski/http-cache-semantics/blob/ed83aec75be817967cdac2663907d060fdc6adc3/README.md#revalidatedpolicyrevalidationrequest-revalidationresponse

**Comment by guanzo** [comment]
Ok it's starting to make sense. 

> revalidatedPolicy method takes TTL from the 304 response and combines it with other data from the old one:

This happens when `matches = true`.

https://github.com/kornelski/http-cache-semantics/blob/ed83aec75be817967cdac2663907d060fdc6adc3/index.js#L648-L656

Turns out the problem with the file i'm revalidating, is the logic leads to `matches = false` 

Here's how i'm revalidating the file.

Request: 
```
GET /some-file.png HTTP/2
if-modified-since: Thu, 29 Jul 2021 22:01:28 GMT
```

Response:
```
HTTP/2 304 
date: Fri, 30 Jul 2021 21:37:30 GMT
expires: Fri, 30 Jul 2021 21:52:30 GMT
cache-control: max-age=900
```

When calling `revalidatedPolicy()`, it hits this code path, where both `modified` and `matches` are false, and I get a new policy with a 304 status.

https://github.com/kornelski/http-cache-semantics/blob/ed83aec75be817967cdac2663907d060fdc6adc3/index.js#L637-L646

So i'm allowed to return the response because it wasn't modified, BUT i'm not allowed to cache the response since its a 304. Seems like the next time this file is requested, I have to request it from the origin.

Could you explain this comment?

> We don't have a good way to tell clients to do error recovery in such case

Is the server misbehaving in this case? What kind of error recovery should the client be doing?

**Comment by kornelski** [comment]
So if I understand correctly, the original response you've cached had a `last-modified` header, but the new 304 response does not have one.

So I think, according to the RFC, it's not supposed to match. `last-modified` can be omitted, but only if the server is consistent about this:

https://github.com/kornelski/http-cache-semantics/blob/ed83aec75be817967cdac2663907d060fdc6adc3/index.js#L623-L634

Therefore this is technically a server error, and the response is not supposed to be usable. You can't return it, can't cache it, can't update previous response with it. You should recover from the error by making a new request to the server without if-modified-since. I realize that's a bit harsh, but that's what the spec says.

…or make the server include a matching last-modified header if you can.

**Comment by guanzo** [comment]
Gotcha. Thanks for walking through this with me.
