### ISSUE TITLE
Unable to handle the Header Object

### ISSUE THREAD

**Issue by jaxoncreed** [kornelski/http-cache-semantics#37]
Hey, this might be because I'm using this library incorrectly, so sorry in advance if that's the case.

It looks like this library tries to access header objects as if they were in a traditional object literal (https://github.com/kornelski/http-cache-semantics/blob/master/index.js#L137)

But, the [`Response`](https://developer.mozilla.org/en-US/docs/Web/API/Response) object uses the [`Headers`](https://developer.mozilla.org/en-US/docs/Web/API/Headers) object. The `Headers` object requires developers to retrieve headers with the `.get` method.

This means that this library can't read headers, and thus can't determine if something can be cached properly. Take the following example:

```typescript
const uri = "https://httpbin.org/response-headers?cache-control=max-age%3D604800";
const request = new Request(uri);
const response = await fetch(request);
const policy = new CachePolicy(request, response, options);
const newRequest = new Request(uri);
// Returns false because "maxAge" is 0 because the library can't read the headers
console.log(policy.satisfiesWithoutRevalidation(newRequest));
```

I am using this library in a NodeJS environment using `Request`, `fetch`, and `Response` from [`cross-fetch`](https://www.npmjs.com/package/cross-fetch).

Am I using this wrong?

**Comment by kornelski** [comment]
This library is older than `fetch()`, from the olden days when `headers` was a mere `Object`. You will have to copy over the headers to a plain object.
