### ISSUE TITLE
Trying to cache authenticated github api responses

### ISSUE THREAD

**Issue by kirillgroshkov** [kornelski/http-cache-semantics#9]
I'm making authenticated github api requests and want them cached with `got` and `cacheable-request` libraries. Github returns `Cache-Control: private`, but I expect it still to be cached when I pass `shared: false` in opts. It's not getting cached.

Here's the response headers, maybe someone can help me how I can make it cacheable?

```js
{ server: 'GitHub.com',
  date: 'Sat, 21 Apr 2018 12:14:45 GMT',
  'content-type': 'application/json; charset=utf-8',
  'transfer-encoding': 'chunked',
  connection: 'close',
  status: '200 OK',
  'x-ratelimit-limit': '5000',
  'x-ratelimit-remaining': '4836',
  'x-ratelimit-reset': '1524313615',
  'cache-control': 'private, max-age=60, s-maxage=60',
  vary: 'Accept, Authorization, Cookie, X-GitHub-OTP',
  etag: 'W/"4876f954d40e3efc6d32aab08b9bdc47"',
  'x-oauth-scopes': 'public_repo, read:user, repo:invite, repo:status, repo_deployment',
  'x-accepted-oauth-scopes': '',
  'x-github-media-type': 'github.v3',
  link: '<https://api.github.com/user/4757745/starred?per_page=1&page=2>; rel="next", <https://api.github.com/user/4757745/starred?per_page=1&page=1120>; rel="last"',
  'access-control-expose-headers': 'ETag, Link, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval',
  'access-control-allow-origin': '*',
  'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
  'x-frame-options': 'deny',
  'x-content-type-options': 'nosniff',
  'x-xss-protection': '1; mode=block',
  'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
  'content-security-policy': 'default-src \'none\'',
  'x-runtime-rack': '0.051653',
  'content-encoding': 'gzip',
  'x-github-request-id': 'C6EE:12E7:3E6CA0D:87F0004:5ADB2B35' }
```

ps: beginning of story: https://github.com/sindresorhus/got/issues/480

**Comment by kornelski** [comment]
I've added it as a test, and it passes: 3e40636cb82c380832c8f658eccf007834055706

It's only cacheable for a minute. How far is server's `Date` header from your server's clock?

**Comment by kirillgroshkov** [comment]
Currently I think the issue is with `Vary` header. I didn't manage to log real request headers (Accept, Authorization, Cookie, X-GitHub-OTP), but my guess is that they differ between request and that causes the module to make it not storable.

**Comment by kirillgroshkov** [comment]
Here's the minimal code I'm using while testing (needs github token to be placed in the header.

```typescript
import { Response } from 'got'

const got = require('got');
const map = new Map();
const url = 'https://api.github.com/users/kirillgroshkov/starred?per_page=1&page=1'

;(async () => {
  let response = await req()
  console.log(response.fromCache);
  // console.log(response.headers, response.fromCache);
  //=> false

  // await new Promise(r => setTimeout(r, 2000))

  response = await req()
  // console.log(response.headers, response.fromCache);
  console.log(response.fromCache);
  // console.log(Object.keys(map)
  // console.log(map)
  // console.log(JSON.parse((map as any).values()[0]))
  //=> true
})();

async function req (): Promise<Response<any>> {
  return got(url, {
    json: true,
    cache: map,
    headers: {
      Authorization: `token <place token here>`,
    },
    shared: false,
  });
}

```

It's based on original example from Sindre in `got`. Expected to log: `false`, `true` (second time as cached). Currently logs `false`, `false` if Authorization header is sent.

**Comment by kornelski** [comment]
https://tools.ietf.org/html/rfc7234#section-3.2

> ### 3.2.  Storing Responses to Authenticated Requests

>   A shared cache MUST NOT use a cached response to a request with an
   Authorization header field (Section 4.2 of [RFC7235]) to satisfy any
   subsequent request unless a cache directive that allows such
   responses to be stored is present in the response.

>   In this specification, the following Cache-Control response
   directives (Section 5.2.2) have such an effect: must-revalidate,
   public, and s-maxage.

**Comment by kornelski** [comment]
It does have s-maxage, so Authorization isn't the problem.

I suspect it's a problem of difference between `Date` and your server's clock being larger than 1 minute. Unfortunately the RFC does require computing max-age since `Date`, not since time response was received. OKHTTP test suite includes a test for it with a comment that Firefox supports it correctly, and Chrome cheats.

I've added `trustServerDate: fasle` option to cheat like Chrome ca485f27adf6bd1eb4c38fe5be022ab0b9dbe782

**Comment by kirillgroshkov** [comment]
Thanks for all the efforts!
I'm going to close it since in my use case I decided to simply monkey-patch `cacheable()` method to always return `true` (in my case it works, so actually I don't need this package directly, I'm here only because it's used in `got`).
